export {
  isAgentDetailView,
  isAgentPairingAbandonView,
  isAgentPairingClaimView,
  isAgentPairingClaimWireView,
  isChatListView,
  isCornerListView,
  isInviteView,
  isRoomHistoryView,
  isRoomView,
  isRoomViewMessage,
  isWorkspaceListView,
  isWorkspaceMemberListView,
  isWorkspaceView,
  readAgentDetailView,
  readAgentPairingAbandonView,
  readAgentPairingClaimView,
  readAgentPairingClaimWireView,
  readChatListView,
  readCornerListView,
  readInviteView,
  readRoomHistoryView,
  readRoomView,
  readRoomViewMessage,
  readWorkspaceListView,
  readWorkspaceMemberListView,
  readWorkspaceView,
  type SurfaceReader,
} from '@beeline/api-contract/phone';
