import { describe, expect, it } from 'vitest';
import type { PhoneOperationMap } from '@beeline/api-contract/phone';
import { PHONE_OPERATION_NAMES } from './phone-service.js';

/**
 * A literal mirror of every `PhoneOperationMap` key. `satisfies` fails
 * `npm run typecheck` if a key is added to the map and not listed here,
 * and the loop below fails this test if a listed key is missing from
 * `PHONE_OPERATION_NAMES` — the guard that let #beginAppSignIn/
 * completeAppSignIn reach `server.ts`'s dispatcher without ever being
 * routable (404 unknown_phone_operation).
 */
const ALL_PHONE_OPERATION_NAMES = {
  acceptConnectorOffer: true,
  addRoomMember: true,
  addWorkspaceMember: true,
  adoptGitHubHandle: true,
  answerChoice: true,
  answerStarPrompt: true,
  approveCornerMerge: true,
  banWorkspaceMember: true,
  beginAppSignIn: true,
  beginGitHubIdentityBind: true,
  beginGitHubInstallation: true,
  beginGoogleSignIn: true,
  cancelAgentTurn: true,
  cancelGoogleSignIn: true,
  claimAgentPairing: true,
  claimManagedHandle: true,
  clearNeedsYou: true,
  closeChat: true,
  completeAppSignIn: true,
  completeGitHubIdentityBind: true,
  completeWelcomeCards: true,
  connectWorkbenchApp: true,
  countNeedsYou: true,
  createAgentPairingCode: true,
  createGitHubRepository: true,
  createHumanCorner: true,
  createInvite: true,
  createRoom: true,
  createRoomPoll: true,
  createRoomSchedule: true,
  createWallet: true,
  createWorkspace: true,
  decideAgentGrant: true,
  decideWritePermission: true,
  deleteAccount: true,
  deleteRoom: true,
  deleteRoomMessage: true,
  deleteRoomSchedule: true,
  deleteWorkspace: true,
  disconnectGoogleSignIn: true,
  disconnectWorkbenchApp: true,
  dispatchRoomWorkflow: true,
  getAuthCapabilities: true,
  getGitHubRepositoryAccess: true,
  getIdentityRecovery: true,
  getManagedIdentity: true,
  grantWalletDelegation: true,
  leaveRoom: true,
  leaveWorkspace: true,
  listGitHubRepositories: true,
  listMessageBookmarks: true,
  listRoomSchedules: true,
  listRoomWorkflows: true,
  listRoomWorkflowRuns: true,
  listWorkspaceBans: true,
  pairConnector: true,
  reactToMessage: true,
  readConnectionDetail: true,
  readGoogleSignIn: true,
  readNeedsYou: true,
  readStarPrompt: true,
  readWallet: true,
  readWalletHistory: true,
  readWebPushKey: true,
  readWelcomeCards: true,
  readWorkbench: true,
  searchWorkbenchApps: true,
  readConnectorInstall: true,
  readWorkflowRun: true,
  recoverGitHubIdentity: true,
  redeemInvite: true,
  refreshAgentModelCatalog: true,
  registerPushDevice: true,
  removeAgent: true,
  removeRoomMember: true,
  removeRoomRepository: true,
  removeWorkspaceMember: true,
  reopenChat: true,
  reportMessageIssue: true,
  reportRunningUpdate: true,
  requestCornerClose: true,
  resolveDirectMessage: true,
  resolveInvite: true,
  revokeAgentGrant: true,
  revokeConnectionGrants: true,
  sendFromWallet: true,
  sendPushTest: true,
  sendRoomMessage: true,
  sendRoomReply: true,
  setMessageBookmark: true,
  setRoomGitHubEvents: true,
  setRoomRepository: true,
  setRoomTargetBranch: true,
  skipChoice: true,
  unbanWorkspaceMember: true,
  unpairConnector: true,
  unregisterPushDevice: true,
  updateAgentAccessPolicy: true,
  updateAgentModelSelection: true,
  updateAgentSoul: true,
  updateAgentYolo: true,
  updateIdentityFace: true,
  updateIdentityPushLevel: true,
  updatePersonProfile: true,
  updateRoom: true,
  updateWorkspace: true,
  uploadMedia: true,
} satisfies Record<keyof PhoneOperationMap, true>;

describe('PHONE_OPERATION_NAMES', () => {
  it('lists every PhoneOperationMap key, so server.ts can dispatch it', () => {
    const missing = Object.keys(ALL_PHONE_OPERATION_NAMES).filter(
      (name) => !PHONE_OPERATION_NAMES.has(name as keyof PhoneOperationMap),
    );
    expect(missing).toEqual([]);
  });
});
