/** GitHub App repository credentials for corner sessions. */
import { chmod, mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

/** Git URL scope of the helper: only github.com remotes consult it. */
export const GIT_GITHUB_TOKEN_URL_SCOPE = 'credential.https://github.com.helper';

export interface GitHubCredentialHelperInput {
  /**
   * The PARENT Room channel id (a corner id never matches the runtime
   * record's Room list, and the auth service re-resolves the repository
   * binding from Room truth itself — the session never names a repo).
   */
  roomId: string;
  /** Writable session-private directory the helper script is written into. */
  stateDir: string;
  /** Production refresh path. Dev sessions fall back to the injected token. */
  nodePath?: string;
  cliEntrypoint?: string;
  runtimeConfigPath?: string;
  /** The unwrapped command path inherited by the corner session. */
  path?: string;
}

export interface GitHubCredentialWiring {
  helperPath: string;
  ghWrapperPath: string;
  /** Env entries merging into the ACP child's environment. */
  env: Record<string, string>;
}

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", `'\\''`)}'`;
}

/** The exact helper script text; exported for tests. */
export function githubCredentialHelperScript(input: GitHubCredentialHelperInput): string {
  if (!input.nodePath || !input.cliEntrypoint || !input.runtimeConfigPath) {
    return [
      '#!/bin/sh',
      '# Beeline GitHub credential helper (generated by the Beeline daemon).',
      '# Development fallback: use the installation token minted at activation.',
      'test "$1" = "get" || exit 0',
      "printf 'username=x-access-token\\npassword=%s\\n' \"$GH_TOKEN\"",
      '',
    ].join('\n');
  }
  return [
    '#!/bin/sh',
    '# Beeline GitHub credential helper (generated by the Beeline daemon).',
    '# Prints a fresh repository-scoped GitHub App installation token.',
    `exec ${shellQuote(input.nodePath)} ${shellQuote(input.cliEntrypoint)} \\`,
    `  corner-git-credential --config ${shellQuote(input.runtimeConfigPath)} \\`,
    `  --room ${shellQuote(input.roomId)} "$@"`,
    '',
  ].join('\n');
}

/**
 * Transparent `gh` launcher. Every invocation mints through the same
 * repository-scoped helper as git, so a warm corner never keeps using the
 * activation token after GitHub expires it.
 */
export function githubCliWrapperScript(helperPath: string, basePath: string): string {
  return [
    '#!/bin/sh',
    '# Beeline GitHub CLI launcher (generated by the Beeline daemon).',
    `PATH=${shellQuote(basePath)}`,
    `token="$(${shellQuote(helperPath)} get </dev/null | sed -n 's/^password=//p')"`,
    'test -n "$token" || exit 1',
    'GH_TOKEN="$token" exec gh "$@"',
    '',
  ].join('\n');
}

/**
 * Write the helper script and return its git-env wiring.
 */
export async function prepareGitHubCredentialHelper(
  input: GitHubCredentialHelperInput,
): Promise<GitHubCredentialWiring> {
  await mkdir(input.stateDir, { recursive: true });
  const helperPath = resolve(input.stateDir, 'beeline-git-credential.sh');
  await writeFile(helperPath, githubCredentialHelperScript(input), { mode: 0o700 });
  await chmod(helperPath, 0o700);
  const basePath = input.path ?? process.env.PATH ?? '/usr/local/bin:/usr/bin:/bin';
  const binDir = resolve(input.stateDir, 'bin');
  await mkdir(binDir, { recursive: true });
  const ghWrapperPath = resolve(binDir, 'gh');
  await writeFile(ghWrapperPath, githubCliWrapperScript(helperPath, basePath), { mode: 0o700 });
  await chmod(ghWrapperPath, 0o700);
  return {
    helperPath,
    ghWrapperPath,
    env: {
      GIT_CONFIG_COUNT: '1',
      GIT_CONFIG_KEY_0: GIT_GITHUB_TOKEN_URL_SCOPE,
      GIT_CONFIG_VALUE_0: helperPath,
      PATH: `${binDir}:${basePath}`,
    },
  };
}

/**
 * Resolve the CLI entrypoint this daemon process runs from. Sessions may only
 * wire the helper when the daemon itself runs from a built JS entrypoint
 * (the installed bundle's `beeline-cli.mjs`); a tsx/dev source entry cannot be
 * exec'd by the child, so wiring is skipped — dev environments keep ambient
 * credentials anyway.
 */
export function resolveBeelineCliEntrypoint(argv: readonly string[] = process.argv): string | undefined {
  const entry = argv[1];
  if (!entry) return undefined;
  const resolved = resolve(entry);
  if (!/\.[cm]?js$/i.test(resolved)) return undefined;
  return resolved;
}
