/**
 * Read-only repository credentials for agent SESSIONS.
 *
 * #376 stripped every push-capable token from ACP children and masked the
 * operator's credential stores — correct for pushes, but it also removed the
 * only credential a private-repo `git fetch` inside a corner could use (owner
 * report 2026-08-23: "GitHub credentials are masked here by design"). The
 * armor's assumption that the daemon performs private fetches does not hold:
 * agents legitimately run `git fetch` themselves for currency checks and
 * rebases.
 *
 * This module restores READ access without weakening the armor. The daemon
 * writes a tiny git credential-helper script into the session's PRIVATE state
 * directory (never the worktree — an untracked file there would block merge
 * readiness). The script execs this bundle's own CLI, which asks the auth
 * service for a fresh GitHub App installation token minted with
 * `permissions: { contents: "read", metadata: "read" }` pinned to the exact
 * repository id. Such a token is structurally incapable of pushing or writing
 * anything on any ref: GitHub refuses the write server-side. The push broker,
 * the env denylist (`REPO_PUSH_CREDENTIAL_ENV_DENYLIST`), and every #376 mask
 * are untouched — no push-capable credential ever enters agent env, and the
 * helper reaches git through `GIT_CONFIG_*` env entries scoped to
 * `https://github.com` only.
 *
 * Freshness is on demand: git invokes the helper per credential lookup, so
 * every fetch mints a current token rather than baking one static value at
 * session start (installation tokens expire after about an hour).
 */
import { chmod, mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

/** Git URL scope of the helper: only github.com remotes consult it. */
export const GIT_READ_TOKEN_URL_SCOPE = 'credential.https://github.com.helper';

export interface GitReadTokenHelperInput {
  /**
   * The PARENT Room channel id (a corner id never matches the runtime
   * record's Room list, and the auth service re-resolves the repository
   * binding from Room truth itself — the session never names a repo).
   */
  roomId: string;
  /** Writable session-private directory the helper script is written into. */
  stateDir: string;
  /** Absolute node interpreter path (the daemon's own `process.execPath`). */
  nodePath: string;
  /** Absolute path to the beeline CLI entrypoint this process runs from. */
  cliEntrypoint: string;
  /** Absolute path to the daemon's runtime.json (identity + relay base). */
  runtimeConfigPath: string;
}

export interface GitReadTokenWiring {
  helperPath: string;
  /** Env entries merging into the ACP child's environment. */
  env: Record<string, string>;
}

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", `'\\''`)}'`;
}

/** The exact helper script text; exported for tests. */
export function readTokenHelperScript(input: GitReadTokenHelperInput): string {
  return [
    '#!/bin/sh',
    '# Beeline read-only git credential helper (generated by the Beeline daemon).',
    '# Prints a fresh, READ-ONLY GitHub App installation token scoped to this',
    "# corner's repository: contents:read + metadata:read only, so it is",
    '# structurally incapable of pushing or writing anything on any ref.',
    '# No push-capable credential ever passes through here (#376 unchanged).',
    `exec ${shellQuote(input.nodePath)} ${shellQuote(input.cliEntrypoint)} \\`,
    `  corner-git-credential --config ${shellQuote(input.runtimeConfigPath)} \\`,
    `  --room ${shellQuote(input.roomId)} "$@"`,
    '',
  ].join('\n');
}

/**
 * Write the helper script and return its git-env wiring. Throws on I/O
 * failure — callers treat this as best-effort and degrade to today's
 * behaviour (no private-repo fetch) rather than blocking the session.
 */
export async function prepareGitReadTokenHelper(
  input: GitReadTokenHelperInput,
): Promise<GitReadTokenWiring> {
  await mkdir(input.stateDir, { recursive: true });
  const helperPath = resolve(input.stateDir, 'beeline-git-read-credential.sh');
  await writeFile(helperPath, readTokenHelperScript(input), { mode: 0o700 });
  await chmod(helperPath, 0o700);
  return {
    helperPath,
    env: {
      GIT_CONFIG_COUNT: '1',
      GIT_CONFIG_KEY_0: GIT_READ_TOKEN_URL_SCOPE,
      GIT_CONFIG_VALUE_0: helperPath,
    },
  };
}

/**
 * Resolve the CLI entrypoint this daemon process runs from. Sessions may only
 * wire the helper when the daemon itself runs from a built JS entrypoint
 * (the installed bundle's `beeline-cli.mjs`); a tsx/dev source entry cannot be
 * exec'd by the child, so wiring is skipped — dev environments keep ambient
 * credentials anyway.
 */
export function resolveBeelineCliEntrypoint(argv: readonly string[] = process.argv): string | undefined {
  const entry = argv[1];
  if (!entry) return undefined;
  const resolved = resolve(entry);
  if (!/\.[cm]?js$/i.test(resolved)) return undefined;
  return resolved;
}
