import brand from './brand.json';

/**
 * Beeline's three app-wide visual themes. Components consume this one semantic
 * token shape; changing themes never changes the component tree.
 *
 * Content colors are intentionally brighter than chrome colors. `textMuted`
 * and the ledger quiet/ghost tiers are for labels and redundant metadata only,
 * never for narration or human messages.
 */
const shared = {
  brandMark: brand.mark,
  diffAdded: '#3FB950',
  diffRemoved: '#F85149',
  // DESIGN.md ("Identity → 4 · A gold ring means alive"): a relay photo
  // defeats every identity axis at once — shape, signature colour, cypher —
  // so the photo path in IdentityMark ships GATED OFF. The code stays dark
  // but intact pending a captain decision on portraits clipped inside the
  // silhouette; do not flip this back without one.
  photoIdentityMarksEnabled: false,
} as const;

export const beelineThemes = {
  obsidian: {
    ...shared,
    name: 'obsidian',
    label: 'Obsidian Refined',
    description: 'Readable sans prose on a quiet obsidian field',
    dark: true,
    bgVoid: '#070708',
    bgTerminal: '#070708',
    bgBase: '#070708',
    bgRaised: '#0c0c0f',
    bgCode: '#0c0c0f',
    bgHighlight: '#111114',
    bgHover: '#141418',
    bgPressed: '#1a1a1f',
    bgTexturePeak: '#2e2e36',
    bgVisual: '#0c0c0f',
    textPrimary: '#f0f0f3',
    textSecondary: '#c9c9d1',
    textMuted: '#83838d',
    textDisabled: '#6c6c76',
    textInverted: '#111111',
    actionFill: '#f0f0f3',
    chrome: '#83838d',
    steel: '#83838d',
    signalBright: '#c9c9d1',
    signalMid: '#83838d',
    signalDim: '#6c6c76',
    danger: '#f0f0f3',
    success: '#f0f0f3',
    warning: '#c9a24b',
    accent: '#c9a24b',
    humanRail: '#c9a24b',
    agentRail: '#2e2e36',
    radius: 8,
    ledgerBright: '#f0f0f3',
    ledgerBody: '#c9c9d1',
    ledgerQuiet: '#83838d',
    ledgerGhost: '#6c6c76',
    ledgerGlow: 'transparent',
    avatarGround: '#070708',
    avatarInk: '#f0f0f3',
    avatarSoft: '#83838d',
    avatarDim: '#2e2e36',
    agentAccent: '#c9a24b',
    borderQuiet: '#1c1c21',
    border: '#1c1c21',
    borderStrong: '#2e2e36',
    focus: '#83838d',
    selectedBorder: '#83838d',
    selection: '#111114',
    muted: '#83838d',
    dim: '#83838d',
    gutter: '#6c6c76',
    faint: '#2e2e36',
    tertiary: '#6c6c76',
    borderActive: '#83838d',
    proseRegular: 'IBMPlexSans-Regular',
    proseItalic: 'IBMPlexSans-Italic',
    proseSemibold: 'IBMPlexSans-SemiBold',
    monoRegular: 'IBMPlexMono-Regular',
    monoItalic: 'IBMPlexMono-Italic',
    monoSemibold: 'IBMPlexMono-SemiBold',
    proseSize: 15,
    proseLineHeight: 23,
    leadSize: 16,
    leadLineHeight: 23,
    turnGap: 18,
    continuationGap: 10,
    turnPaddingVertical: 14,
    railWidth: 2,
    railInset: 12,
  },
  editorial: {
    ...shared,
    name: 'editorial',
    label: 'Editorial Ink',
    description: 'Warm near-black with bundled IBM Plex Serif prose',
    dark: true,
    bgVoid: '#14120e',
    bgTerminal: '#14120e',
    bgBase: '#14120e',
    bgRaised: '#191612',
    bgCode: '#191612',
    bgHighlight: '#1f1b16',
    bgHover: '#211d18',
    bgPressed: '#29241d',
    bgTexturePeak: '#3a342b',
    bgVisual: '#191612',
    textPrimary: '#f2ede3',
    textSecondary: '#ddd5c7',
    textMuted: '#8d8578',
    textDisabled: '#746d62',
    textInverted: '#14120e',
    actionFill: '#f2ede3',
    chrome: '#8d8578',
    steel: '#8d8578',
    signalBright: '#ddd5c7',
    signalMid: '#8d8578',
    signalDim: '#746d62',
    danger: '#f2ede3',
    success: '#f2ede3',
    warning: '#d9b166',
    accent: '#d9b166',
    humanRail: '#d9b166',
    agentRail: '#3a342b',
    radius: 4,
    ledgerBright: '#f2ede3',
    ledgerBody: '#ddd5c7',
    ledgerQuiet: '#8d8578',
    ledgerGhost: '#746d62',
    ledgerGlow: 'transparent',
    avatarGround: '#14120e',
    avatarInk: '#f2ede3',
    avatarSoft: '#8d8578',
    avatarDim: '#3a342b',
    agentAccent: '#d9b166',
    borderQuiet: '#2a261f',
    border: '#2a261f',
    borderStrong: '#3a342b',
    focus: '#8d8578',
    selectedBorder: '#8d8578',
    selection: '#1f1b16',
    muted: '#8d8578',
    dim: '#8d8578',
    gutter: '#746d62',
    faint: '#3a342b',
    tertiary: '#746d62',
    borderActive: '#8d8578',
    proseRegular: 'IBMPlexSerif-Regular',
    proseItalic: 'IBMPlexSerif-Italic',
    proseSemibold: 'IBMPlexSerif-SemiBold',
    monoRegular: 'IBMPlexMono-Regular',
    monoItalic: 'IBMPlexMono-Italic',
    monoSemibold: 'IBMPlexMono-SemiBold',
    proseSize: 16,
    proseLineHeight: 27,
    leadSize: 18,
    leadLineHeight: 26,
    turnGap: 20,
    continuationGap: 12,
    turnPaddingVertical: 16,
    railWidth: 1,
    railInset: 12,
  },
  ledger: {
    ...shared,
    name: 'ledger',
    label: 'Ledger',
    description: 'Dense mono with colored speaker rails for heavy use',
    dark: true,
    bgVoid: '#0b0d10',
    bgTerminal: '#0b0d10',
    bgBase: '#0b0d10',
    bgRaised: '#0f1216',
    bgCode: '#0f1216',
    bgHighlight: '#14171c',
    bgHover: '#14171c',
    bgPressed: '#1a1e24',
    bgTexturePeak: '#303742',
    bgVisual: '#0f1216',
    textPrimary: '#dfe4ea',
    textSecondary: '#b3bac4',
    textMuted: '#7f8997',
    textDisabled: '#6f7885',
    textInverted: '#0b0d10',
    actionFill: '#dfe4ea',
    chrome: '#7f8997',
    steel: '#7f8997',
    signalBright: '#b3bac4',
    signalMid: '#7f8997',
    signalDim: '#6f7885',
    danger: '#dfe4ea',
    success: '#dfe4ea',
    warning: '#c9a24b',
    accent: '#c9a24b',
    humanRail: '#6f8fd0',
    agentRail: '#5fae7a',
    radius: 4,
    ledgerBright: '#dfe4ea',
    ledgerBody: '#b3bac4',
    ledgerQuiet: '#7f8997',
    ledgerGhost: '#6f7885',
    ledgerGlow: 'transparent',
    avatarGround: '#0b0d10',
    avatarInk: '#dfe4ea',
    avatarSoft: '#7f8997',
    avatarDim: '#303742',
    agentAccent: '#c9a24b',
    borderQuiet: '#1a1e24',
    border: '#1a1e24',
    borderStrong: '#303742',
    focus: '#7f8997',
    selectedBorder: '#7f8997',
    selection: '#14171c',
    muted: '#7f8997',
    dim: '#7f8997',
    gutter: '#6f7885',
    faint: '#303742',
    tertiary: '#6f7885',
    borderActive: '#7f8997',
    proseRegular: 'IBMPlexMono-Regular',
    proseItalic: 'IBMPlexMono-Italic',
    proseSemibold: 'IBMPlexMono-SemiBold',
    monoRegular: 'IBMPlexMono-Regular',
    monoItalic: 'IBMPlexMono-Italic',
    monoSemibold: 'IBMPlexMono-SemiBold',
    proseSize: 13,
    proseLineHeight: 19,
    leadSize: 13,
    leadLineHeight: 19,
    turnGap: 11,
    continuationGap: 6,
    turnPaddingVertical: 8,
    railWidth: 3,
    railInset: 9,
  },
} as const;

export type BeelineThemeName = keyof typeof beelineThemes;
export type BeelineThemeTokens = (typeof beelineThemes)[BeelineThemeName];

/** Backward-compatible name for the new default token set. */
export const groknight = beelineThemes.obsidian;
export type GrokNightToken = keyof typeof groknight;
