import brand from './brand.json';

/**
 * Beeline's three app-wide visual themes. Components consume this one semantic
 * token shape; changing themes never changes the component tree.
 *
 * Content colors are intentionally brighter than chrome colors. `textMuted`
 * and the ledger quiet/ghost tiers are for labels and redundant metadata only,
 * never for narration or human messages.
 */
const shared = {
  brandMark: brand.mark,
  diffAdded: '#3FB950',
  diffRemoved: '#F85149',
  // Human and agent relay photos defeat their identity axes, so their shared
  // photo gate stays off. Workspace pictures are the explicit exception and
  // are gated separately in photo-overrides.ts.
  photoIdentityMarksEnabled: false,
} as const;

export const beelineThemes = {
  obsidian: {
    ...shared,
    name: 'obsidian',
    label: 'Obsidian Refined',
    description: 'Readable sans prose on a quiet obsidian field',
    dark: true,
    // Canvas = Speakeasy's brand canvas `#14091A` (apps/mobile/src/theme/
    // tokens.ts), applied at the token level so every screen inherits it.
    // Every elevation stop below keeps the EXACT channel offset its stop had
    // from the old near-black base (#070708), so borders/dividers/text
    // contrast relationships are unchanged — the ladder just rises from the
    // aubergine canvas now.
    bgVoid: '#14091A',
    bgTerminal: '#14091A',
    bgBase: '#14091A',
    bgRaised: '#190e21',
    bgCode: '#190e21',
    bgHighlight: '#1e1326',
    bgHover: '#21162a',
    bgPressed: '#271c31',
    bgTexturePeak: '#3b3048',
    bgVisual: '#190e21',
    textPrimary: '#f0f0f3',
    textSecondary: '#c9c9d1',
    textMuted: '#83838d',
    textDisabled: '#6c6c76',
    textInverted: '#111111',
    actionFill: '#f0f0f3',
    chrome: '#83838d',
    steel: '#83838d',
    signalBright: '#c9c9d1',
    signalMid: '#83838d',
    signalDim: '#6c6c76',
    danger: '#f0f0f3',
    success: '#f0f0f3',
    warning: '#b08a4a',
    accent: '#b08a4a',
    humanRail: '#b08a4a',
    agentRail: '#3b3048',
    radius: 3,
    ledgerBright: '#f0f0f3',
    ledgerBody: '#c9c9d1',
    ledgerQuiet: '#83838d',
    ledgerGhost: '#6c6c76',
    ledgerGlow: 'transparent',
    avatarGround: '#14091A',
    avatarInk: '#f0f0f3',
    avatarSoft: '#83838d',
    avatarDim: '#3b3048',
    agentAccent: '#b08a4a',
    borderQuiet: '#291e33',
    border: '#291e33',
    borderStrong: '#3b3048',
    focus: '#83838d',
    selectedBorder: '#83838d',
    selection: '#1e1326',
    muted: '#83838d',
    dim: '#83838d',
    gutter: '#6c6c76',
    faint: '#3b3048',
    tertiary: '#6c6c76',
    borderActive: '#83838d',
    proseRegular: 'SpaceGrotesk-Regular',
    proseItalic: 'IBMPlexSans-Italic',
    proseSemibold: 'SpaceGrotesk-SemiBold',
    monoRegular: 'IBMPlexMono-Regular',
    monoItalic: 'IBMPlexMono-Italic',
    monoSemibold: 'IBMPlexMono-SemiBold',
    // ONE message size: hierarchy on a long agent turn comes from weight
    // (proseMedium lead vs proseRegular body) and brightness, never size.
    proseSize: 16,
    proseLineHeight: 25,
    leadSize: 16,
    leadLineHeight: 25,
    // Turn separation is a hairline divider plus generous vertical padding,
    // not air alone.
    turnGap: 4,
    continuationGap: 0,
    turnPaddingVertical: 18,
    railWidth: 2,
    railInset: 12,
    // Editorial direction additions.
    proseMedium: 'SpaceGrotesk-Medium',
    turnDivider: '#1b1024',
    codeError: '#c98a8a',
  },
  editorial: {
    ...shared,
    name: 'editorial',
    label: 'Editorial Ink',
    description: 'Warm near-black with bundled IBM Plex Serif prose',
    dark: true,
    // Same Speakeasy-canvas mapping as Obsidian: base → #14091A, every other
    // background stop shifted by its old offset from the old warm base
    // (#14120e).
    bgVoid: '#14091A',
    bgTerminal: '#14091A',
    bgBase: '#14091A',
    bgRaised: '#190d1e',
    bgCode: '#190d1e',
    bgHighlight: '#1f1222',
    bgHover: '#211424',
    bgPressed: '#291b29',
    bgTexturePeak: '#3a2b37',
    bgVisual: '#190d1e',
    textPrimary: '#f2ede3',
    textSecondary: '#ddd5c7',
    textMuted: '#8d8578',
    textDisabled: '#746d62',
    textInverted: '#14091A',
    actionFill: '#f2ede3',
    chrome: '#8d8578',
    steel: '#8d8578',
    signalBright: '#ddd5c7',
    signalMid: '#8d8578',
    signalDim: '#746d62',
    danger: '#f2ede3',
    success: '#f2ede3',
    warning: '#d9b166',
    accent: '#d9b166',
    humanRail: '#d9b166',
    agentRail: '#3a2b37',
    radius: 3,
    ledgerBright: '#f2ede3',
    ledgerBody: '#ddd5c7',
    ledgerQuiet: '#8d8578',
    ledgerGhost: '#746d62',
    ledgerGlow: 'transparent',
    avatarGround: '#14091A',
    avatarInk: '#f2ede3',
    avatarSoft: '#8d8578',
    avatarDim: '#3a2b37',
    agentAccent: '#d9b166',
    borderQuiet: '#2a1d2b',
    border: '#2a1d2b',
    borderStrong: '#3a2b37',
    focus: '#8d8578',
    selectedBorder: '#8d8578',
    selection: '#1f1222',
    muted: '#8d8578',
    dim: '#8d8578',
    gutter: '#746d62',
    faint: '#3a2b37',
    tertiary: '#746d62',
    borderActive: '#8d8578',
    proseRegular: 'IBMPlexSerif-Regular',
    proseItalic: 'IBMPlexSerif-Italic',
    proseSemibold: 'IBMPlexSerif-SemiBold',
    monoRegular: 'IBMPlexMono-Regular',
    monoItalic: 'IBMPlexMono-Italic',
    monoSemibold: 'IBMPlexMono-SemiBold',
    proseSize: 16,
    proseLineHeight: 27,
    leadSize: 16,
    leadLineHeight: 27,
    turnGap: 20,
    continuationGap: 12,
    turnPaddingVertical: 16,
    railWidth: 1,
    railInset: 12,
    proseMedium: 'IBMPlexSerif-SemiBold',
    turnDivider: '#221523',
    codeError: '#c98a8a',
  },
  ledger: {
    ...shared,
    name: 'ledger',
    label: 'Ledger',
    description: 'Dense mono with colored speaker rails for heavy use',
    dark: true,
    // Same Speakeasy-canvas mapping as Obsidian: base → #14091A, every other
    // background stop shifted by its old offset from the old cool base
    // (#0b0d10).
    bgVoid: '#14091A',
    bgTerminal: '#14091A',
    bgBase: '#14091A',
    bgRaised: '#180e20',
    bgCode: '#180e20',
    bgHighlight: '#1d1326',
    bgHover: '#1d1326',
    bgPressed: '#231a2e',
    bgTexturePeak: '#39334c',
    bgVisual: '#180e20',
    textPrimary: '#dfe4ea',
    textSecondary: '#b3bac4',
    textMuted: '#7f8997',
    textDisabled: '#6f7885',
    textInverted: '#14091A',
    actionFill: '#dfe4ea',
    chrome: '#7f8997',
    steel: '#7f8997',
    signalBright: '#b3bac4',
    signalMid: '#7f8997',
    signalDim: '#6f7885',
    danger: '#dfe4ea',
    success: '#dfe4ea',
    warning: '#c9a24b',
    accent: '#c9a24b',
    humanRail: '#6f8fd0',
    // No green anywhere in the product (Editorial direction): a green agent
    // rail is replaced with the theme's neutral peak.
    agentRail: '#39334c',
    radius: 3,
    ledgerBright: '#dfe4ea',
    ledgerBody: '#b3bac4',
    ledgerQuiet: '#7f8997',
    ledgerGhost: '#6f7885',
    ledgerGlow: 'transparent',
    avatarGround: '#14091A',
    avatarInk: '#dfe4ea',
    avatarSoft: '#7f8997',
    avatarDim: '#39334c',
    agentAccent: '#c9a24b',
    borderQuiet: '#231a2e',
    border: '#231a2e',
    borderStrong: '#39334c',
    focus: '#7f8997',
    selectedBorder: '#7f8997',
    selection: '#1d1326',
    muted: '#7f8997',
    dim: '#7f8997',
    gutter: '#6f7885',
    faint: '#39334c',
    tertiary: '#6f7885',
    borderActive: '#7f8997',
    proseRegular: 'IBMPlexMono-Regular',
    proseItalic: 'IBMPlexMono-Italic',
    proseSemibold: 'IBMPlexMono-SemiBold',
    monoRegular: 'IBMPlexMono-Regular',
    monoItalic: 'IBMPlexMono-Italic',
    monoSemibold: 'IBMPlexMono-SemiBold',
    proseSize: 13,
    proseLineHeight: 19,
    leadSize: 13,
    leadLineHeight: 19,
    turnGap: 11,
    continuationGap: 6,
    turnPaddingVertical: 8,
    railWidth: 3,
    railInset: 9,
    proseMedium: 'IBMPlexMono-SemiBold',
    turnDivider: '#231a2e',
    codeError: '#c98a8a',
  },
} as const;

export type BeelineThemeName = keyof typeof beelineThemes;
export type BeelineThemeTokens = (typeof beelineThemes)[BeelineThemeName];

/** Backward-compatible name for the new default token set. */
export const groknight = beelineThemes.obsidian;
export type GrokNightToken = keyof typeof groknight;
