#!/usr/bin/env node
/**
 * Regenerates `sources/vendor/pdfjs/pdfjs.gen.ts` from a pinned `pdfjs-dist`
 * tarball.
 *
 * The PDF renderer has to reach two runtimes that cannot share an npm import:
 * the app's own document on web, and a `react-native-webview` document on
 * Android that is handed a string, not a module graph. Both take the renderer
 * as SOURCE TEXT, so the pinned build is vendored as string exports rather
 * than added as a dependency Metro would have to resolve twice.
 *
 *   node scripts/vendor-pdfjs.mjs [--version 5.7.284] [--check]
 *
 * `--check` regenerates into memory and fails when the checked-in file drifts.
 */
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUTPUT = join(HERE, '..', 'sources', 'vendor', 'pdfjs', 'pdfjs.gen.ts');
const DEFAULT_VERSION = '5.7.284';

function argumentValue(flag, fallback) {
  const at = process.argv.indexOf(flag);
  return at >= 0 && process.argv[at + 1] ? process.argv[at + 1] : fallback;
}

function generate(version) {
  const work = mkdtempSync(join(tmpdir(), 'vendor-pdfjs-'));
  try {
    execFileSync('npm', ['pack', `pdfjs-dist@${version}`, '--silent'], { cwd: work, stdio: 'pipe' });
    execFileSync('tar', ['xzf', `pdfjs-dist-${version}.tgz`], { cwd: work });
    const read = (name) => readFileSync(join(work, 'package', 'build', name), 'utf8');
    const main = read('pdf.min.mjs');
    const worker = read('pdf.worker.min.mjs');
    const license = JSON.parse(readFileSync(join(work, 'package', 'package.json'), 'utf8')).license;
    writeFileSync(
      join(HERE, '..', 'sources', 'vendor', 'pdfjs', 'LICENSE'),
      readFileSync(join(work, 'package', 'LICENSE'), 'utf8'),
    );
    return [
      '/* eslint-disable */',
      '// GENERATED by scripts/vendor-pdfjs.mjs — do not edit by hand.',
      `// pdfjs-dist ${version} (${license}), minified build, carried as source text`,
      '// because both render hosts take the renderer as a string: the app document',
      '// on web and the WebView document on Android.',
      '',
      '/** `pdf.min.mjs` — the API half, imported as an ES module from a blob URL. */',
      `export const PDFJS_MAIN_SOURCE = ${JSON.stringify(main)};`,
      '',
      '/** `pdf.worker.min.mjs` — loaded on the main thread as pdf.js’ fake worker. */',
      `export const PDFJS_WORKER_SOURCE = ${JSON.stringify(worker)};`,
      '',
    ].join('\n');
  } finally {
    rmSync(work, { recursive: true, force: true });
  }
}

const version = argumentValue('--version', DEFAULT_VERSION);
const generated = generate(version);
if (process.argv.includes('--check')) {
  const current = readFileSync(OUTPUT, 'utf8');
  if (current !== generated) {
    console.error(`pdfjs vendor file is stale — run: node scripts/vendor-pdfjs.mjs --version ${version}`);
    process.exit(1);
  }
  console.log(`pdfjs-dist ${version} vendor file is current`);
} else {
  writeFileSync(OUTPUT, generated);
  console.log(`wrote ${OUTPUT} from pdfjs-dist ${version}`);
}
